Fix/accessibility and error handling
Tampere/vuorovaikutusalusta pull request #156
Opened 2023-08-09 13:28 UTC by mmoila

- In map subquestion dialog errors are now displayed when leaving focus
- After closing map subquestion dialog focus is moved back to the respective question 
- Input is not validated unnecessarily when 
  - Section info is opened
  - Text field for radio question appears

2023-08-10 10:13 UTC, jpeltzi commented on client/src/components/MapQuestion.tsx
> +            )?.focus();
This should also happen `onSubmit`.

2023-08-10 10:28 UTC, jpeltzi requested changes

2023-08-10 10:28 UTC, jpeltzi commented on client/src/components/MapQuestion.tsx
> +            )?.focus();
This should also happen `onSubmit`.

2023-08-10 10:28 UTC, jpeltzi commented on client/src/components/MapSubQuestionDialog.tsx
> +                !e.currentTarget.contains(e.relatedTarget as Node)
Still seems to validate when focus leaves one checkbox in a group of checkboxes. Works on radio groups, though.

2023-08-10 10:28 UTC, jpeltzi commented on client/src/components/SurveyQuestion.tsx
> +          )
This doesn't seem to work? Validation is triggered when trying to move focus inside the section info dialog.

2023-08-11 06:26 UTC, mmoila commented on client/src/components/MapQuestion.tsx
> +            )?.focus();
Fixed. Also changed question reference to id instead of classname to prevent errors if page contains multiple mapquestions.

2023-08-11 06:39 UTC, mmoila commented on client/src/components/MapSubQuestionDialog.tsx
> +                !e.currentTarget.contains(e.relatedTarget as Node)
Fixed

2023-08-11 06:54 UTC, mmoila commented on client/src/components/SurveyQuestion.tsx
> +          )
Fixed. Prevent validation if infoDialogOpen state is true.

2023-08-11 09:19 UTC, jpeltzi commented on client/src/components/SurveyQuestion.tsx
> +          )
Works now on surveystepper. Apply to map subquestion dialog and we're set 👍

2023-08-11 09:26 UTC, mmoila commented on client/src/components/SurveyQuestion.tsx
> +          )
Fixed

2023-08-11 11:39 UTC, merged