Feature/multi choice matrix
Tampere/vuorovaikutusalusta pull request #189
Opened 2023-09-01 12:13 UTC by mmoila

- New multiple choice matrix question is implemented
- Possible to select multiple answers with limitations defined by the question author

Closes #100

2023-09-04 08:24 UTC, ossitammi commented on client/src/components/admin/EditMultiMatrixQuestion.tsx
> +  function handleAnswerLimitsMinChange(value: number) {
There seems to be some logic error with the min/max values in the admin UI. min-value is initially set to 0, but if it is changed, it cannot be turned back to 0 anymore.

2023-09-04 08:28 UTC, ossitammi commented on client/src/components/admin/SurveyList.tsx
> +              setNewSurveyLoading(false);
nit: This could be also done in `finally {...}` -block

2023-09-04 08:32 UTC, ossitammi commented on client/src/stores/SurveyAnswerContext.tsx
> +      // Multiple choice matrix is considered incomplete if any of the rows is empty
If the question is not marked as "required", it should be allowed for the user to leave the question completely unanswered (e.g. zero answers on every row). Or the user might want to answer only to some rows and leave some row unanswered.

2023-09-05 07:39 UTC, jpeltzi requested changes
Usability (not code) review (using Firefox):

1. [Admin view] Move answer count limit after subjects and options. The latter affect the former and UI elements should never be affected by things that come further down in the layout.
2. [Admin view] Inserting a new subject autofocuses the field, but inserting a new option does not. Should be consistent. 
3. The "I don't know" option column could benefit from having a gray background to visually indicate its distinct nature. Suggest `#efefef`. Applies to all matrix questions.
4. The choice count information text "Valitse vähintään n, enintään m vaihtoehtoa" is a complete sentence and should therefore be concluded with a period.
5. See if you can make the focus styling trigger when focusing with arrow keys. That is: focusing with arrow keys works already, but is not represented visually. See `.focusVisible()`.
6. The unselected checkboxes in a row should disable once the maximum number of selections has been made in that row, similarly to the grouped checkbox question.
7. The allowed response count should be stated by the SR when focusing the question.
8. Violating the response count limit is invisible to the SR. Suggestion: State the count limits when focusing a row. Repeat the current number of selected boxes `.onChange()` similarly to the grouped checkbox question. If the limit is reached, add a mention to that effect.
9. Validation is now triggered at row level, but validation feedback is at question level. The discrepancy should be addressed by either (preferrably) making the feedback able to name the row with incomplete answer or by triggering the validation upon exiting the question.

2023-09-15 07:56 UTC, jpeltzi commented
When multiple selections is enabled, subjects titles are centered in their cells. Should be aligned left.

2023-09-21 13:41 UTC, jpeltzi approved these changes
Accessibility concerns have been addressed👍

2023-09-22 11:37 UTC, merged