Feature/clipboard copying
Tampere/vuorovaikutusalusta pull request #191
Opened 2023-09-01 13:18 UTC by ossitammi

Feature for copying pages and sections

Closes #98 and #99

2023-09-01 13:52 UTC, ossitammi commented on client/src/stores/SurveyContext.tsx
> -        originalActiveSurvey: JSON.parse(JSON.stringify(action.survey)),
There was a problem when a blank new page was deleted and the DateTimePickers threw an error because of a invalid time format -> found out it was caused by this line that converted the surveys startDate and endDate to strings which caused the pickers to crash.

But there was some other problem that was fixed with this JSON parsing trick, I wonder what that was.

2023-09-04 09:38 UTC, jlaamanen requested changes
Looks great! 👌 After reapplying the deep-clone fix this should be good to go.

2023-09-04 09:38 UTC, jlaamanen commented on client/src/components/admin/EditSurveySideBar.tsx
> +                            onClick={async (event) => {
[nit] I guess this doesn't need to be `async` anymore?

2023-09-04 09:38 UTC, jlaamanen commented on client/src/stores/SurveyContext.tsx
> -        originalActiveSurvey: JSON.parse(JSON.stringify(action.survey)),
This part is called whenever:
1. a survey is initially loaded to the context
2. changes are discarded
3. survey is saved

This deep-copy fix was one part of various bugfixes introduced in https://github.com/ubigu/vuorovaikutusalusta/pull/120, and I'm afraid this will make some of those bugs appear again.

However, I think this could be fixed properly with `structuredClone`, which seems to support cloning `Date`s and other non-JSON-compliant types.

2023-09-04 09:38 UTC, jlaamanen commented on client/src/utils/schemaValidation.ts
> +export function replaceIdsWithNull(obj: any, depth: number) {
[nit] The default value for `depth` could be `-1`, so it wouldn't need to be explicitly provided in every function call
```suggestion
export function replaceIdsWithNull(obj: any, depth = -1) {
```

2023-09-06 07:20 UTC, merged