Feature/improved submissions page
Tampere/vuorovaikutusalusta pull request #195
Opened 2023-10-03 06:12 UTC by mmoila

- Add submissions page for admin users to view published survey submissions

Closes #108

2023-10-04 10:13 UTC, ossitammi commented on client/src/components/admin/EditSurveyHeader.tsx
> +      labels={[originalActiveSurvey.title[surveyLanguage]]}
This line causes an error + ui to crash when creating a new survey as the title is initially undefined

2023-10-04 10:19 UTC, ossitammi commented on client/src/components/admin/AdminFrontPage.tsx
> +      <AdminAppBar labels={[tr.AnswersList.answers]} />
The label should say "Kyselyt" instead of "Vastaukset" in the admin front page

2023-10-04 10:34 UTC, ossitammi commented on client/src/components/SurveyQuestion.tsx
> +          opacity: 0.87,
Was there a specific design purpose for the opacity?

2023-10-04 10:52 UTC, ossitammi commented on client/src/components/admin/SubmissionsPage/DataChart.tsx
> +function getDataByWeek(data: any[]) {
The data could have a type definition

2023-10-04 10:57 UTC, ossitammi commented on client/src/components/admin/SubmissionsPage/DataChart.tsx
> +                : format(parse(data, 'dd.MM.yyyy', new Date()), 'd.M')
Probably this 'd.M' missing a dot from the end (check out the screenshot for reference)

2023-10-04 11:18 UTC, ossitammi requested changes
Otherwise looks really good :+1:

2023-10-04 11:19 UTC, ossitammi commented
Date should have a trailing dot (e.g. "4.10.")

![Screenshot 2023-10-04 at 13 25 03](https://github.com/Tampere/vuorovaikutusalusta/assets/15360748/78ac2ddf-714d-47af-b56b-ae99345375d9)

2023-10-04 11:21 UTC, ossitammi commented
Oskari map flows under the `<AdminAppBar>` hiding the map navigation options: lower down the map the same amount as the `<AdminAppBar>` reserves height   

![Screenshot 2023-10-04 at 13 21 28](https://github.com/Tampere/vuorovaikutusalusta/assets/15360748/532e3b9f-8d95-4e27-aa64-3006ade7e5df)

2023-10-06 12:45 UTC, mmoila commented on client/src/components/SurveyQuestion.tsx
> +          opacity: 0.87,
Yes, it was added to give question headers softer look as they are quite dark by default. The headers got darker after missing fontsource import were added to `client/src/index.tsx`.

2023-10-09 07:32 UTC, merged