Feature/follow up questions
Tampere/vuorovaikutusalusta pull request #202
Opened 2023-10-31 08:32 UTC by mmoila

- New feature follow-up sections
  - Can be added after numeric, slider, radio and checkbox questions
  - Follow-up sections for a question can be reordered
- New feature conditional pages
  - Any page except the first one in the survey can be a conditional page 
  - Conditions are based on previous pages question answers
  - Pages can be reordered, but reordering will clear conditions that don't fit the new page order

2023-11-01 10:22 UTC, jpeltzi requested changes
Submitting the survey doesn't seem to work when the last page is conditional and the condition is not met.
![kuva](https://github.com/Tampere/vuorovaikutusalusta/assets/5507205/5d725876-bd89-4229-99c1-3aaf7fab3c5e)
The "Cancel" button might not be visible when changing the type of a follow-up question.

2023-11-01 10:22 UTC, jpeltzi commented on client/src/components/admin/SurveySectionAccordion/SectionDetails.tsx
> +              disabled={section.id < 0} // no follow-up sections for draft questions
Add a `title` attribute to inform the user why the button is disabled. Otherwise it's up to pure guesswork to figure it out.

2023-11-01 10:22 UTC, jpeltzi commented on client/src/components/SurveyStepper.tsx
> +                      ? `(${tr.SurveyStepper.conditionalPage})`
The conditionality statement should reflect the response status (i.e. if the page is relevant to the respondent) as stated in the UI design.
The styling of the step title should be unaffected until the condition can be evaulated as not met.

2023-11-01 10:22 UTC, jpeltzi commented on client/src/stores/fi.json
> +    "conditionalPage": "ehdollinen sivu",
"Page" as a metaphor is poorly supported by the survey layout. My recommendation is to use the term "step" / "vaihe" instead.

2023-11-01 10:22 UTC, jpeltzi commented on client/src/components/admin/EditSurveyPage.tsx
> +      <EditSurveyPageConditions />
A page having a condition doesn't seem to be reflected in the sidebar page list.

2023-11-13 09:17 UTC, ossitammi commented on client/src/stores/SurveyAnswerContext.tsx
When the survey is initially loaded, this file throws an error:

![Screenshot 2023-11-13 at 11 13 11](https://github.com/Tampere/vuorovaikutusalusta/assets/15360748/0a39eb8c-7395-42a9-9397-3b0fc5e99d46)

2023-11-13 09:20 UTC, ossitammi commented on client/src/stores/SurveyAnswerContext.tsx
Also, if the user focuses on the answer field of the question and then clicks somewhere else without answering, an exception is thrown. At least this happened when the leading question was numeric. 

Error:
![Screenshot 2023-11-13 at 11 14 12](https://github.com/Tampere/vuorovaikutusalusta/assets/15360748/49a4f5c8-1d82-4085-bdd0-095d9d4de386)

2023-11-13 09:21 UTC, ossitammi commented on client/src/stores/SurveyAnswerContext.tsx
Correction: The error is thrown and the page crashes even if you try to insert some value on the answer field

2023-11-13 09:26 UTC, ossitammi requested changes
Changes needed to finish code review. 
- The `SurveyAnswerContext` causes errors that crashes the page.
- The follow up questions are missing from the translations

2023-11-13 15:27 UTC, mmoila commented on client/src/stores/SurveyAnswerContext.tsx
This was caused by saved follow-up section without defined section type. Fixed by setting radio question as default type for follow-up sections.

2023-11-13 15:28 UTC, mmoila commented on client/src/stores/SurveyAnswerContext.tsx
Couldn't really reproduce but added a fix to prevent these in the future.

2023-11-20 16:25 UTC, merged